### ISSUE TITLE
Limit number of cache entries?

### ISSUE THREAD

**Issue by EternityForest** [jstasiak/python-zeroconf#105]
If you just passively listen for mdns records, there's a possibility of an attacker or a bug boadcasting a whole bunch and using up a bunch of ram. If the entries were limited, they could DoS the discovery system, but the rest of the application could keep running as normal.

If everyone agrees that this is an issue I can make a pull request for it.

**Comment by bdraco** [comment]
The mDNS trust model is to trust the whole local network.  https://datatracker.ietf.org/doc/html/rfc6762#section-21. If there is a bad actor on the network, filling up the cache probably isn't the highest risk item.  I'd expect its more likely it happens because of a bug in someone's implementation.
