### ISSUE TITLE
Two exceptions raised

### ISSUE THREAD

**Issue by hegga** [jstasiak/python-zeroconf#269]
I'm running version 2.8.4 of HAP-python and version 0.27.0 of zeroconf. While trying to pair with HomeKit, as the driver starts up the following traceback is thrown:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 1312, in run
    reader.handle_read(socket_)
  File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 1379, in handle_read
    self.zc.handle_query(msg, None, _MDNS_PORT)
  File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 2676, in handle_query
    service.text,
  File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 623, in __init__
    assert isinstance(text, (bytes, type(None)))
AssertionError

Future exception was never retrieved
future: <Future finished exception=AssertionError()>
Traceback (most recent call last):
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pyhap/accessory_driver.py", line 287, in _do_start
    self.advertiser.register_service(self.mdns_service_info)
  File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 2374, in register_service
    self._broadcast_service(info)
  File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 2414, in _broadcast_service
    DNSText(info.name, _TYPE_TXT, _CLASS_IN | _CLASS_UNIQUE, info.other_ttl, info.text), 0
  File "/usr/local/lib/python3.7/dist-packages/zeroconf/__init__.py", line 623, in __init__
    assert isinstance(text, (bytes, type(None)))
AssertionError
```

Reverting back to version 0.26.3 of zeroconf removes the issue.

**Comment by jstasiak** [comment]
0.27.0 contains a backwards incompatible change (ab72aa8e5a6a83e50d24d7fb187e8fa8a549a847, mentioned in the changelog) and the client code hasn't been updated.

**Comment by BlackLight** [comment]
Guys, wasn't it better to keep both `address` and `addresses` in `register_service`, or, even better, add a simple logic like this?

```python
if isinstance(addresses, bytes):
    addresses = [addresses]   # Single address provided
```

I know, it looks hackish, but you CAN'T introduce backwards-incompatible changes like this. apt, pacman and other package managers still provide `python-zeroconf < 0.27.0`, and other packages depend on it. As a developer of a project that depends on `python-zeroconf` I don't want to find myself in the situation where I have to either break other packages that depend on the package-manager-installed version of it by installing the most recent version, or stick to `python-zeroconf < 0.27.0` in my `setup.py` and basically rely on a version of the library that will get older and older just because you decided to introduce a breaking change that could have been avoided with two lines of code. What's worse is that any application that depends on the package-manager-installed version needs to synchronize to the new signature once the `python-zeroconf` is upgraded, and that may break quite a few applications. Please, have mercy of the developers using your project.

**Comment by BlackLight** [comment]
p.s. The situation is even worse than I thought. I thought that I could have at least fixed my code to work with any version like this:

```python
info = ServiceInfo(
            srv_type,
            srv_name,
            addresses=[socket.inet_aton(adr)],
            port=port,
            properties={}
)
```

But that's not the case. The `python-zeroconf` version provided by apt on Debian/Raspbian is 0.21.3 and `register_service` in that version doesn't provide `addresses`:

```
TypeError: __init__() got an unexpected keyword argument 'addresses'
```

So there's basically no way of writing software that works both with the apt version and the pip version without breaking something else - I was about to prepare a pull request to make things cross-compatible, but after seeing so many issues I give up.

**Comment by emontnemery** [comment]
@BlackLight I really don't think it's a good idea to write new code depending on ancient versions of an actively developed library, your application is better off pinning versions of libraries it uses instead and I stalling them locally in a venv. Anyhow, you can check the function prototype or `zeroconf.__version__` to make code compatible with both versions.

**Comment by totaam** [comment]
@emontnemery please look into how software is distributed and packaged, more often than not the developers have very little or no control over library updates which may be handled by a package manager. This breaks existing code as well as making it very difficult to remain version agnostic.
Asking every application that uses this library to introduce version checks that were not there before is unnecessary onerous for the developers, it is also the wrong place to do it, and in all likelihood this will result in an untold number of wasted human hours.

**Comment by jstasiak** [comment]
I'm sorry, nothing productive will come out of talking about this in this fashion. The backward compatibility requirements you describe above aren't satisfied by this library and there are no guarantees otherwise. Really, there are no guarantees at all, considering it's volunteer work done in people's free time, which is increasingly precious. Statements like

> but you CAN'T introduce backwards-incompatible changes like this

make me feel this is not appreciated to the extent it should be.

**Comment by BlackLight** [comment]
@jstasiak most of us contribute to open-source projects in our spare time, that doesn't mean that we shouldn't have any consideration of those who use our projects.

To understand the impact of this is sufficient to take a look at the packages that depend on `python-zeroconf`.

- [Arch Linux reports 4 packages that depend on it](https://www.archlinux.org/packages/community/any/python-zeroconf/) on the main repo (not AUR), including a quite large project like `calibre`, and since I can't do the same search with the AUR or Debian I'm pretty sure that this is only the tip of the iceberg (at least `pulseaudio-dlna` depends on it from what I know).

- And `python-zeroconf` is also [used by 99 GitHub packages](https://github.com/jstasiak/python-zeroconf/network/dependents?dependent_type=PACKAGE).

How are all these projects supposed to deal with your numerous breaking changes (that apparently occur within a couple of days/weeks without even giving developers time to adapt/migrate)? Are they supposed to periodically check your changelog (among those of many other dependencies that they use) and do dirty hacks like checking `zeroconf.__version__`  in their code depending on the breaking changes you introduced? If that's the case, could you at least mention in your README something like _This project will undergo many breaking changes, use it at your own risk and periodically check the status_?

How is the maintainer of your package on Arch/Debian/RH supposed to deal with these breaking changes without breaking other packages? Are they going to hold back on previous versions to make sure that existing packages don't break? And what happens when at least one of the dependent packages migrates to the new version? If package `A` depends on e.g. 0.25.0 while package `B` starts depending on 0.28.0 then the maintainer will have to make hard some decisions, don't upgrade `B` until `A` is upgraded as well, or upgrade `python-zeroconf` and break `A`.

Now imagine all the developers of open-source projects out there responding to such objections with the same response as yours - "I just do this in my free time, take it or leave it and don't bother me". Keeping track of dependencies across projects would be hell, and each `apt upgrade` would probably break something, and if in all cases debugging the root cause of the issue requires the same amount of time I've spent to figure out this issue then all the time of the developers out there will be simply wasted in debugging and resolving breaking changes introduced by their dependencies. This isn't a healthy way to contribute to the community, you can't ask people to be respectful of your time when you aren't respectful of theirs.

**Comment by totaam** [comment]
> Requiring every library you use to never make incompatible changes is completely unreasonable.

No-one is making this request.
Changes that break compatibility do happen, but they normally go through a process of deprecation of old features and / or warnings. Giving time to adapt.

> Again, you need to use a reasonable way to package your python application

As I said above, please look into package managers and how they work. Many python packages are distributed separately from the applications that use it.
Pinning is neither desirable nor is it even practical most of the time.

**Comment by BlackLight** [comment]
@emontnemery I'm not questioning the need to introduce breaking changes sometimes. I'm questioning the frequency of such breaking changes, the actual need for them and the way they are communicated. I agree that packaging Python applications should involve specifying the range of compatible versions for the dependencies, but keep in mind that pip isn't the only way to manage dependencies. `python-zeroconf` has also system packages, and the developer of an application usually doesn't have control on them. If you think that breaking changes like these will happen often then your project is simply not mature enough to be managed by a package manager like apt or pacman that is leveraged by other applications as well - an example: upgrading the `python-zeroconf`package on Raspbian via pip broke the `pulseaudio-dlna`package.

I'm the developer of a large project that relies on about ~100 optional dependencies. If all of them were to introduce breaking changes with a frequency of 1-2 months then I'd stop spending time working on new features and I'd have to dedicate all of my time debugging such issues and fixing dependency versions.

**Comment by jstasiak** [comment]
I'd like to set one thing straight, otherwise people reading this thread will get the wrong idea: the `address` constructor parameter and property had been deprecated (with a warning) for over 11 months (since 2019-06-04/0.23.0) before they got removed in 0.27.0 on 2020-05-27, so any statements implying otherwise are incorrect.

**Comment by BlackLight** [comment]
> the `address` constructor parameter and property had been deprecated (with a warning) for over 11 months (since 2019-06-04/0.23.0) before they got removed in 0.27.0 on 2020-05-27

Where was the warning? I had several earlier versions of Zeroconf on my systems, ranging from 0.21.x to 0.25.x, and I haven't seen any message such as `WARNING: address will be deprecated soon` when calling the `ServiceInfo` constructor. And after taking a look at some projects depending on `zeroconf` I've noticed that I'm not the only one who apparently missed the warning ([an example](https://github.com/hifiberry/hifiberry-dsp/blob/cb752dc96e8569020038b3b61e20af914b321e49/hifiberrydsp/server/sigmatcp.py#L893)).

And it's not even about this change alone - I could have probably found a workaround for it because the `addresses` parameter was also present in some of the earlier versions - if you look at [earlier versions](https://github.com/jstasiak/python-zeroconf/blob/d4e06bc54098bfa7a863bcc11bb9e2035738c8f5/zeroconf.py#L1414) `addresses` wasn't present at all.

It sounds like something can be improved both on the communication of breaking changes and on how to handle them when an OS package manager provides your package and other packages rely on it - an example: [Debian still provides the version 0.19.1](https://packages.debian.org/buster/python-zeroconf) of the package, and all the packages that rely on it can't use `addresses` at all, even if the alternative is deprecated. If your project is still under heavy development then communicate it better to your users, and avoid releasing apt/yum/pacman packages, otherwise other packages will depend on it and will likely break.
